using System;
using System;

namespace Sabresaurus.Sidekick
{
    [Serializable]
    public class OldSettings
    {
        public bool RotationsAsEuler = true; // Whether Quaternions are edited as a euler triplet, or their 4D base
        public bool HideAutoGenerated = true; // Whether automatically generated get/set methods and backing fields are hidden
        public bool TreatEnumsAsInts = false; // Whether to treat enums as ints
        public string SearchTerm = "";
    }
}