#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using Sabresaurus.Sidekick.Requests;

namespace Sabresaurus.Sidekick
{
    [Serializable]
    public class SidekickSettings
    {
#if SIDEKICK_DEBUG
        public bool LocalDevMode = false;
#endif
        public bool IgnoreObsolete = true; // When set fields, properties and methods with [Obsolete] attribute are ignored
        public bool NiceifyNames = false; // Whether to turn names like "m_cameraSpeed" into "Camera Speed"

        public bool AutoRefreshRemote = false;
        public string SearchTerm = "";

        public InspectionConnection InspectionConnection = InspectionConnection.LocalEditor;
        public InfoFlags GetGameObjectFlags = InfoFlags.Fields | InfoFlags.Properties;

        public List<string> CollapsedTypeNames = new List<string>();

        //public bool RotationsAsEuler = true; // Whether Quaternions are edited as a euler triplet, or their 4D base
        public bool IncludeInherited = false; // Whether reflection uses the declared type only or recurses down
        //public bool HideAutoGenerated = true; // Whether automatically generated get/set methods and backing fields are hidden
        //public bool TreatEnumsAsInts = false; // Whether to treat enums as ints
        //public string SearchTerm = "";
    }
}
#endif